### ISSUE TITLE
Cannot find module 'sao'

### ISSUE THREAD

**Issue by Berkmann18** [lirantal/create-node-lib#14]
## Expected Behaviour

The series of prompts (cf. README) should appear.

## Current Behaviour

```shell
Error: Cannot find module 'sao'
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
  at Function.Module._load (internal/modules/cjs/loader.js:575:25)
  at Module.require (internal/modules/cjs/loader.js:705:19)
  at require (internal/modules/cjs/helpers.js:14:16)
  at Object.<anonymous> (/home/max/.nvm/versions/node/v11.12.0/lib/node_modules/create-node-lib/bin/cli.js:5:13)
  at Module._compile (internal/modules/cjs/loader.js:799:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
  at Module.load (internal/modules/cjs/loader.js:666:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
  at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

## Possible Solution
Check if the `sao` module is listed as the correct dependency.

## Steps to Reproduce (for bugs)
1. `npx create-node-lib some-name` 

Or
1. `npm i -g create-node-lib`
2. `create-node-lib some-name`

## Context

I'm trying this package out as I'm planning on creating a package for an exploratory project.
## Your Environment

- Library Version used: 2.1.1
- Node.js version (e.g. Node.js 5.4): 11.12.0
- Operating System and version (desktop or mobile): Ubuntu WSL on Windows 10 x86_64

**Comment by lirantal** [comment]
thanks @Berkmann18 👍 
this is now fixed by https://github.com/lirantal/create-node-lib/pull/15

can you try to re-run 
```
npx create-node-lib some-name
```

and confirm?

**Comment by Berkmann18** [comment]
It works now (babel throw a deprecation warning regarding the preset btw).

**Comment by lirantal** [comment]
Great to hear!

If you fancy to a PR a fix for the deprecation warning that's awesome otherwise I'll get to it some time in the future ;-)
